### ISSUE TITLE
Findings react-shortcut

### ISSUE THREAD

**Issue by deventually** [devlato/react-shortcut#2]
Hi devlato,

I have been trying to integrate it in my webapp and would like to request some features.

1) Like stated in another comment, input elements don't prevent triggering hotkeys. Input elements should, in general, not react on global key events, unless used in combination with ctrl or alt keys, which have no specific function in input elements. This would still enable the user to trigger some global key event from inside an input element, without changing the content of the input element.
2) Using shortcuts with the shift key is buggy. Shift+0 results in event {shiftKey: true, key: ')'}. This could be prevented by checking the which or keyCode property instead of the key property.
3) It would be really awesome if you could implement support for mousetrap.

Anyway thanks a lot for react-shortcut.

**Comment by devlato** [comment]
Hey @deventually,

about your proposal:
1. I prefer just to exclude inputs and other form elements from global handler.
2. It was the easiest solution on the first step, I'll see what I can do here.
3. What do you mean by mousetrap?

**Comment by devlato** [comment]
@deventually hey mate, please follow up [this PR](https://github.com/devlato/react-shortcut/pull/10) – when it gets merged, a brand new version will be released.
